package com.zys.amuse.jdbc.dao;

import com.zys.amuse.jdbc.entity.BookInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BookInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_book_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_book_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int insert(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_book_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int insertSelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_book_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    BookInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_book_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int updateByPrimaryKeySelective(BookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_book_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int updateByPrimaryKey(BookInfo record);

    List<BookInfo> listBook();
}