package com.zys.amuse.jdbc.dao;

import com.zys.amuse.jdbc.entity.SheetInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SheetInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_sheet_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_sheet_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int insert(SheetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_sheet_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int insertSelective(SheetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_sheet_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    SheetInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_sheet_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int updateByPrimaryKeySelective(SheetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amuse_sheet_info
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    int updateByPrimaryKey(SheetInfo record);

    List<SheetInfo> listSheetByBookId(@Param("bookId") Integer bookId);

    List<SheetInfo> listSheet();

    void deleteByBookId(@Param("bookId") Integer bookId);

}