package com.zys.amuse.jdbc.entity;

public class BookInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_book_info.id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_book_info.book_name
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private String bookName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_book_info.id
     *
     * @return the value of amuse_book_info.id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_book_info.id
     *
     * @param id the value for amuse_book_info.id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_book_info.book_name
     *
     * @return the value of amuse_book_info.book_name
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_book_info.book_name
     *
     * @param bookName the value for amuse_book_info.book_name
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
}