package com.zys.amuse.jdbc.entity;

public class ColumnInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_column_info.id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_column_info.col_name
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private String colName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_column_info.col_comment
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private String colComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_column_info.col_type
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private String colType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_column_info.col_order
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private int colOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amuse_column_info.sheet_id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    private Integer sheetId;

    private Integer colSize;

    private Integer nullTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_column_info.id
     *
     * @return the value of amuse_column_info.id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_column_info.id
     *
     * @param id the value for amuse_column_info.id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_column_info.col_name
     *
     * @return the value of amuse_column_info.col_name
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public String getColName() {
        return colName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_column_info.col_name
     *
     * @param colName the value for amuse_column_info.col_name
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setColName(String colName) {
        this.colName = colName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_column_info.col_comment
     *
     * @return the value of amuse_column_info.col_comment
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public String getColComment() {
        return colComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_column_info.col_comment
     *
     * @param colComment the value for amuse_column_info.col_comment
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setColComment(String colComment) {
        this.colComment = colComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_column_info.col_type
     *
     * @return the value of amuse_column_info.col_type
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public String getColType() {
        return colType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_column_info.col_type
     *
     * @param colType the value for amuse_column_info.col_type
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setColType(String colType) {
        this.colType = colType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_column_info.col_order
     *
     * @return the value of amuse_column_info.col_order
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public int getColOrder() {
        return colOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_column_info.col_order
     *
     * @param colOrder the value for amuse_column_info.col_order
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setColOrder(int colOrder) {
        this.colOrder = colOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amuse_column_info.sheet_id
     *
     * @return the value of amuse_column_info.sheet_id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public Integer getSheetId() {
        return sheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amuse_column_info.sheet_id
     *
     * @param sheetId the value for amuse_column_info.sheet_id
     *
     * @mbggenerated Thu Nov 29 18:16:12 CST 2018
     */
    public void setSheetId(Integer sheetId) {
        this.sheetId = sheetId;
    }

    public Integer getColSize() {
        return colSize;
    }

    public void setColSize(Integer colSize) {
        this.colSize = colSize;
    }

    public int getNullTag() {
        return nullTag;
    }

    public void setNullTag(int nullTag) {
        this.nullTag = nullTag;
    }

    public void setNullTag(Integer nullTag) {
        this.nullTag = nullTag;
    }
}